# Generated by Django 5.2.1 on 2025-05-15 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', through='animeapp.AnimeGenre', to='animeapp.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=models.ManyToManyField(related_name='animes', through='animeapp.AnimePlatform', to='animeapp.platform'),
        ),
        migrations.AlterField(
            model_name='animegenre',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_genres', to='animeapp.anime'),
        ),
        migrations.AlterField(
            model_name='animegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_animes', to='animeapp.genre'),
        ),
        migrations.AlterField(
            model_name='animeplatform',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_platforms', to='animeapp.anime'),
        ),
        migrations.AlterField(
            model_name='animeplatform',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_animes', to='animeapp.platform'),
        ),
        migrations.AlterField(
            model_name='review',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='animeapp.anime'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranimelist',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to='animeapp.anime'),
        ),
        migrations.AlterField(
            model_name='useranimelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
