# Generated by Django 5.2.1 on 2025-05-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0002_alter_anime_genres_alter_anime_platforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='poster_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='animeplatform',
            name='watch_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='platform',
            name='base_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
