services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # เอา DATABASE_URL เข้าไปเลย ไม่ต้อง .env
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydb"
      # ตัวแปรเสริมอื่นๆ
      DJANGO_SECRET_KEY: "your-local-secret-key"
      DEBUG: "True"
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api/
      CHOKIDAR_USEPOLLING: "true"
      HOST: 0.0.0.0
      PORT: 3000
    command: >
      sh -c "npm run dev -- -H 0.0.0.0 -p 3000"

volumes:
  pgdata:
