version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/animeapp/management/commands:/app/animeapp/management/commands
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/
      - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata:
