services:
  - type: web
    name: animepedia-backend
    env: docker
    plan: free
    repo: https://github.com/itsmehoneyyy/Animepedia
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: >
      sh -c "python wait_for_db.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animepedia-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: hA9lIdqqKzZGsiQxM9No5etJobXkDNGb
        value: your-tlexplus-key
      - key: DJANGO_SECRET_KEY
        generateValue: true

  - type: web
    name: animepedia-frontend
    env: docker
    plan: free
    repo: https://github.com/itsmehoneyyy/Animepedia
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://animepedia-backend.onrender.com/api/
      - key: CHOKIDAR_USEPOLLING
        value: "true"

databases:
  - name: animepedia-db
    databaseName: mydb
    user: myuser
