services:
  - type: web
    name: animepedia-backend
    env: docker
    repo: https://github.com/itsmehoneyyy/Animepedia
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animepedia-db
          property: connectionString
      - key: django-insecure-rlzqlfb^d=w#y)@jlp_776+2n11jc540ia-)7j=w$_zo-+&03c
        generateValue: true
      - key: DEBUG
        value: "False"
    plan: free
    autoDeploy: true

  - type: web
    name: animepedia-frontend
    env: docker
    repo: https://github.com/itsmehoneyyy/Animepedia
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://animepedia-backend.onrender.com/api/
    plan: free
    autoDeploy: true

databases:
  - name: animepedia-db
    databaseName: mydb
    user: myuser
    plan: free
