services:
  - type: web
    name: animepedia-backend
    runtime: docker
    repo: https://github.com/itsmehoneyyy/Animepedia
    branch: main
    dockerfilePath: backend/Dockerfile
    plan: free
    # เอา DATABASE_URL ออกได้ (เราเช็คแยก host/port)
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: animepedia-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: animepedia-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: animepedia-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: animepedia-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: animepedia-db
          property: database

  - type: web
    name: animepedia-frontend
    runtime: docker
    repo: https://github.com/itsmehoneyyy/Animepedia
    branch: main
    dockerfilePath: frontend/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://animepedia-backend.onrender.com/api/
      - key: CHOKIDAR_USEPOLLING
        value: "true"

databases:
  - name: animepedia-db
    region: us-west-2
    plan: free
    databaseName: mydb
    user: myuser