services:
  - type: web
    name: animepedia-fullstack
    env: docker
    repo: https://github.com/itsmehoneyyy/Animepedia.git
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animepedia-db
          property: connectionString
      - key: NEXT_PUBLIC_API_URL
        value: https://animepedia-fullstack.onrender.com/api/
      - key: DJANGO_SETTINGS_MODULE
        value: animeproject.settings
      - key: DEBUG
        value: "False"

databases:
  - name: animepedia-db
    plan: free
