services:
  - type: web
    name: backend
    runtime: docker
    plan: free
    build:
      context: ./backend
    repo: https://github.com/itsmehoneyyy/Animepedia
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animepedia-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: TLEXPLUS_API_KEY
        value: hA9lIdqqKzZGsiQxM9No5etJobXkDNGb
      - key: DJANGO_SECRET_KEY
        generateValue: true

  - type: web
    name: frontend
    runtime: docker
    env: docker
    plan: free
    repo: https://github.com/itsmehoneyyy/Animepedia
    dockerfilePath: frontend/Dockerfile
    build:
      context: ./frontend  # ✅ เพิ่ม!
    buildCommand: ""
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://animepedia-backend.onrender.com/api/
      - key: CHOKIDAR_USEPOLLING
        value: "true"



databases:
  - name: animepedia-db
    databaseName: mydb
    user: myuser
