services:
  - type: web
    name: animepedia-backend
    runtime: docker
    repo: https://github.com/itsmehoneyyy/Animepedia
    branch: main
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animepedia-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"


  - type: web
    name: animepedia-frontend
    runtime: docker
    repo: https://github.com/itsmehoneyyy/Animepedia
    branch: main
    dockerfilePath: frontend/Dockerfile
    plan: free
    # ไม่ต้องระบุ dockerCommand ถ้าใช้ CMD ใน Dockerfile (npm run dev)
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://animepedia-backend.onrender.com/api/
      - key: CHOKIDAR_USEPOLLING
        value: "true"

databases:
  - name: animepedia-db
    region: singapore
    plan: free
    databaseName: mydb
    user: myuser
